version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # Porta per il protocollo AMQP
      - "15672:15672" # Porta per l'interfaccia di gestione
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
